### ISSUE TITLE
GUI explorer

### ISSUE THREAD

**Issue by babymu5k** [bunkercoin/python-restapi#3]
a bunkercoin rest api explorer using pure python
[explorer.zip](https://github.com/bunkercoin/python-restapi/files/8504148/net.zip)
![image](https://user-images.githubusercontent.com/95881676/163769936-e416a18c-17b7-437e-8f58-9c8d16699714.png)

**Comment by IdotMaster1** [comment]
Number 1: This is an issue, not an Pull request
2. It doesn't parse JSON
3. It can't be added to the current code

**Comment by babymu5k** [comment]
well i tried
my first "contribution"
